name: SuperVanishV2
main: ErkamKahriman\Vanish\Vanish
version: 2.0.0
author: ErkamKahriman, edited by VMPE Development Team
api: 3.0.0-ALPHA11
commands:
  supervanish:
    description: "Vanish yourself"
    aliases: [sv]
  supervanishstatus:
    description: "See vanish status"
    aliases: [svstatus, svs]
permissions:
  supervanish.spectate:
    description: "Vanish use permission"
    default: op
  supervanish.status:
    description: "Vanish Status permission"
    default: op
