name: SuperVanishV2
main: ErkamKahriman\Vanish\Vanish
version: 3.0.1
author: ErkamKahriman, edited by VMPE Development Team
api: [3.0.0, 4.0.0]
commands:
  supervanish:
    description: "Toggle on/off vanish."
    aliases: ["sv"]
permissions:
  supervanish.spectate:
    description: "Permission to vanish yourself."
    default: op
  supervanish.see:
    description: "Permission to see other players in Supervanish."
    default: op
